name: build

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * MON'

jobs:
  build:
    runs-on: macos-12
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
    steps:         
      - name: Get mpv latest commit sha
        id: get_sha
        uses: actions/github-script@v6
        with:
          script: |
            const commit = await github.rest.repos.getCommit({
              owner: 'mpv-player',
              repo: 'mpv',
              ref: `master`
            })
            core.exportVariable('sha', String(commit.data.sha)) 
            
      - name: Add SHORT_SHA env 
        run: echo "SHORT_SHA=`echo ${{ env.sha }}| cut -c1-7`" >> $GITHUB_ENV             

      - name: Remove stray upstream python binary symlinks under /usr/local
        run: |
          find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete -print
          brew unlink python && brew link --overwrite python
          
      - name: Install dependencies
        run: |        
          brew update
          brew install meson ninja python

      - name: Build mpv
        run: |
          brew install -v deus0ww/tap/libass --HEAD
          brew install -v deus0ww/tap/libplacebo --HEAD
          brew install -v deus0ww/tap/ffmpeg --HEAD
          brew install -v deus0ww/tap/mpv --HEAD
      
      - name: Get current timestamp
        id: timestamp
        run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT      
      
      - name: zip bundle
        run: |
          mkdir All-in-One
          curl -OL https://github.com/eko5624/mpv-config/archive/refs/heads/main.zip
          unzip main.zip
          mv mpv-config-main/macos_config All-in-One
          sudo ls /usr/local/Cellar/mpv/HEAD*
          sudo find /usr -type d -name "mpv.app" -exec mv {} All-in-One \;
          zip -r All-in-One-${{ steps.timestamp.outputs.date }}.zip All-in-One 

      - name: Create Release      
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{ steps.timestamp.outputs.date }}
          name: ${{ steps.timestamp.outputs.date }}
          body: Bump to mpv-player/mpv@${{ env.SHORT_SHA }}
          files: All*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
