name: build

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * MON'

jobs:
  build:
    runs-on: macos-12
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
    steps:         
      - name: Get mpv latest commit sha
        id: get_sha
        uses: actions/github-script@v6
        with:
          script: |
            const commit = await github.rest.repos.getCommit({
              owner: 'mpv-player',
              repo: 'mpv',
              ref: `master`
            })
            core.setOutput('sha', String(commit.data.sha)) 
            
      - name: Add SHORT_SHA env 
        run: echo "SHORT_SHA=`echo ${{ steps.get_sha.outputs.sha }}| cut -c1-7`" >> $GITHUB_ENV             
          
      - name: Build mpv
        run: |        
          brew update 
          brew uninstall --ignore-dependencies highway
          brew uninstall --ignore-dependencies jpeg-xl
          brew uninstall --ignore-dependencies aom
          brew install -v deus0ww/tap/jpeg-xl --HEAD
          brew link --overwrite jpeg-xl
          brew install -v deus0ww/tap/ffmpeg --HEAD  
          brew install -v deus0ww/tap/mpv --HEAD 
      
      - name: Get current timestamp
        id: timestamp
        run: echo "::set-output name=date::$(date +%Y-%m-%d)"      
      
      - name: zip bundle
        run: |
          mkdir All-in-One
          curl -OL https://github.com/eko5624/mpv-config/archive/refs/heads/main.zip
          unzip main.zip
          mv mpv-config-main/macos_config All-in-One          
          mv /usr/local/Cellar/mpv/HEAD*/mpv.app All-in-One  
          zip -r All-in-One-${{ steps.timestamp.outputs.date }}.zip All-in-One 

      - name: Create Release      
        uses: softprops/action-gh-release@v1
        with:
          tag_name: mpv-${{ env.SHORT_SHA }}
          name: ${{ steps.timestamp.outputs.date }}
          body: Bump to mpv-player/mpv@${{ env.SHORT_SHA }}
          files: All*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
