name: build

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * MON'

jobs:
  build:
    runs-on: macos-12
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
    steps:         
      - name: Get mpv latest commit sha
        id: get_sha
        uses: actions/github-script@v6
        with:
          script: |
            const commit = await github.rest.repos.getCommit({
              owner: 'mpv-player',
              repo: 'mpv',
              ref: `master`
            })
            core.exportVariable('sha', String(commit.data.sha)) 
            
      - name: Add SHORT_SHA env 
        run: echo "SHORT_SHA=`echo ${{ env.sha }}| cut -c1-7`" >> $GITHUB_ENV             

      - name: Build ffmpeg
        run: |
          brew update 
          brew uninstall --ignore-dependencies aom
          brew uninstall --ignore-dependencies jpeg-xl 
          brew tap deus0ww/tap
          brew install -v deus0ww/tap/libplacebo --HEAD
          brew install -v deus0ww/tap/ffmpeg --HEAD

      - name: Checkout
        uses: actions/checkout@main
        
      - name: Build mpv
        run: |
          git clone https://github.com/mpv-player/mpv.git --branch master
          pushd mpv
          echo "sha=$(git log -n1 --format="%h")" >> $GITHUB_ENV
          export PKG_CONFIG_PATH=`brew --prefix zlib`/lib/pkgconfig/:$PKG_CONFIG_PATH
          export PKG_CONFIG_PATH=`brew --prefix luajit-openresty`/lib/pkgconfig/:$PKG_CONFIG_PATH
          export PKG_CONFIG_PATH=`brew --prefix libarchive`/lib/pkgconfig/:$PKG_CONFIG_PATH
          meson setup build
          meson compile -C build
          popd
   
      - name: Bundle mpv
        continue-on-error: true
        run: |
          chmod +x ./bundle.sh
          ./bundle.sh
          
      - name: Get current timestamp
        id: timestamp
        run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT      
        
      - name: Package
        run: |
          mkdir All-in-One
          curl -OL https://github.com/eko5624/mpv-config/archive/refs/heads/main.zip
          unzip main.zip
          mv mpv-config-main/macos_config All-in-One
          sudo mv mpv/build All-in-One
          zip -r -y All-in-One-${{ env.date }}.zip All-in-One/

      - name: Create Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{ env.date }}
          name: ${{ env.date }}
          body: Bump to mpv-player/mpv@${{ env.sha }}
          files: All*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
