name: CI

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * MON'

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Checkout mpv-player/mpv
        uses: eko5624/checkout@v2
        with:
          repository: "mpv-player/mpv"
          fetch-depth: 0

      - name: Get mpv-player/mpv last version
        id: version
        run: echo "::set-output name=version::$(sh version.sh)"
        
      - name: Get mpv-player/mpv last commit SHA
        id: sha
        run: echo "::set-output name=sha::$(git rev-parse --short=7 HEAD)"        

      - name: Override Xcode 13.0 if it's the default toolchain
        run: |
          XCODE_PATH="$(xcode-select -p)"
          case "${XCODE_PATH}" in
            *Xcode_13.0*)
              sudo xcode-select -s "/Applications/Xcode_13.1.app"
              echo "Updated Xcode path ${XCODE_PATH} -> $(xcode-select -p)"
              ;;
          esac
          
      - name: Build mpv
        run: |
          brew tap deus0ww/tap
          brew install --HEAD -v deus0ww/tap/mpv
      - name: zip bundle
        run: zip -r mpv-${{ steps.version.outputs.version }}.zip mpv.app
        working-directory: /usr/local/Cellar/mpv/HEAD-${{ steps.sha.outputs.sha }}

      - name: Get current timestamp
        id: timestamp
        run: echo "::set-output name=date::$(date +%Y-%m-%d)"

      - name: Create Release
        uses: eko5624/action-gh-release@v1
        with:
          tag_name: mpv-${{ steps.version.outputs.version }}
          name: ${{ steps.timestamp.outputs.date }}
          body: Bump to mpv-player/mpv@${{ steps.sha.outputs.sha }}
          files: /usr/local/Cellar/mpv/HEAD-${{ steps.sha.outputs.sha }}/mpv-${{ steps.version.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
