name: CI

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * MON'

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Checkout mpv-player/mpv
        uses: eko5624/checkout@v2
        with:
          repository: "mpv-player/mpv"
          fetch-depth: 0

      - name: Get mpv-player/mpv last version
        id: version
        run: echo "::set-output name=version::$(sh version.sh)"

      - name: Build mpv
        run: |
          brew tap deus0ww/tap
          brew install --HEAD -v deus0ww/tap/mpv

      - name: Get mpv latest commit sha
        id: sha
        run: echo "::set-output name=sha::$(git log -n1 --format="%h")"

      - name: zip bundle
        run: zip -r mpv-${{ steps.version.outputs.version }}.zip /usr/local/Cellar/mpv

      - name: Get current timestamp
        id: timestamp
        run: echo "::set-output name=date::$(date +%Y-%m-%d)"

      - name: Create Release
        uses: eko5624/action-gh-release@v1
        with:
          tag_name: mpv-${{ steps.version.outputs.version }}
          name: ${{ steps.timestamp.outputs.date }}
          body: Bump to mpv-player/mpv@${{ steps.sha.outputs.sha }}
          files: mpv-${{ steps.version.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
