name: CI

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * MON'

jobs:
  build:
    runs-on: macos-12
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
    steps:
      #- name: Checkout mpv-player/mpv
      #  uses: actions/checkout@v3
      #  with:
      #    repository: "mpv-player/mpv"
      #    fetch-depth: 0

      #- name: Get mpv-player/mpv last version
      #  id: version
      #  run: echo "::set-output name=version::$(sh version.sh)"
        
      #- name: Get mpv-player/mpv last commit SHA
      #  id: sha
      #  run: echo "::set-output name=sha::$(git rev-parse --short=7 HEAD)"    
        
      - name: Get mpv latest commit sha
        id: get_sha
        uses: actions/github-script@v6
        with:
          script: |
            const commit = await github.rest.repos.getCommit({
              owner: 'mpv-player',
              repo: 'mpv',
              ref: `master`
            })
            core.setOutput('sha', String(commit.data.sha)) 
            
      - name: Add SHORT_SHA env 
        run: echo "SHORT_SHA=`echo ${{ steps.get_sha.outputs.sha }}| cut -c1-7`" >> $GITHUB_ENV             
          
      - name: Build mpv
        run: |        
          brew uninstall --ignore-dependencies aom
          brew tap deus0ww/tap 
          brew install --HEAD -v deus0ww/tap/mpv
      - name: zip bundle
        run: |
          cd /usr/local/Cellar/mpv/HEAD*
          zip -r mpv-${{ env.SHORT_SHA }}.zip mpv.app
          
      - name: Get current timestamp
        id: timestamp
        run: echo "::set-output name=date::$(date +%Y-%m-%d)"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: mpv-${{ env.SHORT_SHA }}
          name: ${{ steps.timestamp.outputs.date }}
          body: Bump to mpv-player/mpv@${{ env.SHORT_SHA }}
          files: /usr/local/Cellar/mpv/**/mpv*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
