name: Delete tag and release

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * MON'

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        delete_release: true 
        tag_name: mpv*
        repo: eko5624/mpv-macos-test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
